company_project_management/CompanyTasksManagement/Controllers/PersonalController.cs
using CompanyTasksManagement.Models;
using Microsoft.AspNetCore.Mvc;

namespace CompanyTasksManagement.Controllers
{
    public class PersonalController : Controller
    {
        private readonly DataAccess dal = new DataAccess();
        public IActionResult Dashboard()
        {
            User user = new User();
            user.Name = HttpContext.Session.GetString("Name");
            user.AccountType = HttpContext.Session.GetString("type");
            return View(user);
        }

        public IActionResult Admin()
        {
            ForAdmin forAdmin = new ForAdmin();
            forAdmin.Tasks =  dal.GetAllUserTasks();
            forAdmin.Users = dal.GetAllUsers();
           
            return View(forAdmin);
        }

        public IActionResult EditUser(int userId) 
        {
            User user = new User();
            user = dal.GetUserByUserId(userId);
            
            return View(user); 
        }

        public IActionResult Today()
        {
            User user = new User();
            user.Tasks = dal.GetTodayTasksByUserId(HttpContext.Session.GetInt32("UserId"));
            
            return View(user);
        }

        public IActionResult AddTaskForToday([Bind("Name, Summary, Details, Deadline")] TaskM newTask)
        {
            newTask.AssignFor = HttpContext.Session.GetInt32("UserId");
            newTask.AssignBy = HttpContext.Session.GetInt32("UserId");
            newTask.SetForDate = DateTime.Now;
       
            dal.AddTask(newTask);
            return RedirectToAction("Today");
        }

        public IActionResult AllTasks()
        {
            User user = new User();
            user.Tasks = dal.GetTasksByUserId(HttpContext.Session.GetInt32("UserId"));

            return View(user);
        }

        public IActionResult AddTask([Bind("Name, Summary, Details, SetForDate, Deadline")] TaskM newTask)
        {
            newTask.AssignFor = HttpContext.Session.GetInt32("UserId");
            newTask.AssignBy = HttpContext.Session.GetInt32("UserId");

            dal.AddTask(newTask);
            return RedirectToAction("AllTasks");
        }
        public IActionResult Calendar()
        {
            return View();
        }
    }
}

company_project_management/CompanyTasksManagement/Views/Shared/MNGERO.cshtml
@{
    Layout = null; // or Layout = string.Empty;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - MNGERO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/MNGERO.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="your-version" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <nav class="navbar nav-underline navbar-expand-lg navbar-light sticky-top" style="background-color: #FFFFFF;">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center w-100">
                <ul class="navbar-nav nav-fill">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Product">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About Us">About Us</a>
                    </li>
                </ul>
                <a class="navbar-brand mx-auto nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Mngero.png" width="300" height="80" class="d-inline-block align-top" alt="">
                </a>
                <div style="width: 8%;"></div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SignUp">SignUp</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>

company_project_management/CompanyTasksManagement/Views/Shared/PersonalLayout.cshtml
@model User

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="~/css/sidebar.css">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - MNGERO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="your-version" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</head>
<body>
    <div class="sidebar">
        <div class="logo-details">
            <div class="abbr">MNG</div>
            <div class="logo_name">ERO</div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nav-list">
            <li>
                <i class='bx bx-search'></i>
                <input type="text" placeholder="Search...">
                <span class="tooltip">Search</span>
            </li>
            @if(Model.AccountType == "admin")
            {
                <li>
                    <a asp-controller="Personal" asp-action="Admin">
                        <i class='bx bx-user'></i>
                        <span class="links_name">Admin Tab</span>
                    </a>
                    <span class="tooltip">Admin Tab</span>
                </li>
            }
            <li>
                <a asp-controller="Personal" asp-action="Dashboard">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
                <span class="tooltip">Dashboard</span>
            </li>
            <li>
                <a asp-controller="Personal" asp-action="Today">
                    <i class='bx bx-calendar-x'></i>
                    <span class="links_name">Today</span>
                </a>
                <span class="tooltip">Today</span>
            </li>
            <li>
                <a asp-controller="Personal" asp-action="AllTasks">
                    <i class='bx bx-task'></i>
                    <span class="links_name">All Tasks</span>
                </a>
                <span class="tooltip">All Tasks</span>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-cog'></i>
                    <span class="links_name">Setting</span>
                </a>
                <span class="tooltip">Setting</span>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </section>
    <script>
        let sidebar = document.querySelector(".sidebar");
        let closeBtn = document.querySelector("#btn");
        let searchBtn = document.querySelector(".bx-search");
        closeBtn.addEventListener("click", () => {
            sidebar.classList.toggle("open");
            menuBtnChange();//calling the function(optional)
        });
        searchBtn.addEventListener("click", () => { // Sidebar open when you click on the search iocn
            sidebar.classList.toggle("open");
            menuBtnChange(); //calling the function(optional)
        });
        // following are the code to change sidebar button(optional)
        function menuBtnChange() {
            if (sidebar.classList.contains("open")) {
                closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");//replacing the iocns class
            } else {
                closeBtn.classList.replace("bx-menu-alt-right", "bx-menu");//replacing the iocns class
            }
        }
    </script>
</body>
</html>

company_project_management/CompanyTasksManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyTasksManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanyTasksManagement.styles.css" asp-append-version="true" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="your-version" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Managero</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="New">New</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="One">One</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CompanyTasksManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>